services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile.dev # Change to Dockerfile.prod for production
    container_name: todoapp
    ports:
      - "8081:80" # Exposing the application port
      - "5005:5005" # Exposing the debugger port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - ConnectionStrings__DefaultConnection=Server=todoapp-mysql;Database=TodoAppDb;User=root;Password=password;
      - Jwt__Key=your-very-secure-secret-key-that-is-long-enough
      - Jwt__Issuer=your-issuer
      - Jwt__Audience=your-audience
    depends_on:
      - mysql
    volumes:
      - todoapp:/app:rw # Bind mount the current directory to /app inside the container
      - ~/.vsdbg:/remote_debugger:rw

  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    container_name: todoapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TodoAppDb
    volumes:
      - todoapp-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todoapp:
  todoapp-mysql-data: